# Generated by Django 6.0.5 on 2026-06-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffabout',
            name='user',
        ),
        migrations.AddField(
            model_name='staffabout',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
