# Generated by Django 6.0.5 on 2026-06-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_remove_staffabout_user_staffabout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffabout',
            name='profile_img',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
