# Generated by Django 6.0.5 on 2026-06-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_staffabout_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffabout',
            options={'ordering': ['display_order']},
        ),
        migrations.RenameField(
            model_name='staffabout',
            old_name='is_staff',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='staffabout',
            name='profile_img',
        ),
        migrations.AddField(
            model_name='staffabout',
            name='profile_img_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='staffabout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
