# Generated by Django 6.0.5 on 2026-06-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_staffabout_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffabout',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
