# Generated by Django 6.0.5 on 2026-06-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_alter_staffabout_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffabout',
            name='bio_description',
            field=models.TextField(null=True),
        ),
    ]
