# Generated by Django 6.0.5 on 2026-06-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_alter_staffabout_bio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffabout',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='staffabout',
            name='profile_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
