# Generated by Django 6.0.5 on 2026-06-10 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_staffabout_profile_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffabout',
            name='profile_img',
        ),
    ]
