# Generated by Django 6.0.5 on 2026-08-29 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioproject_portfolioprojecttag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioUpcoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('live_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_live', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioUpcomingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projecttag')),
                ('upcoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolioupcoming')),
            ],
            options={
                'unique_together': {('upcoming', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='portfolioupcoming',
            name='tags',
            field=models.ManyToManyField(blank=True, through='portfolio.PortfolioUpcomingTag', to='portfolio.projecttag'),
        ),
    ]
