# Generated by Django 6.0.5 on 2026-08-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioupcoming_portfolioupcomingtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioproject',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='portfolioupcoming',
            name='image_url',
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioupcoming',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/upcoming/'),
        ),
    ]
